# Generated by Django 5.1.6 on 2025-03-28 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='body',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='postcomments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
