# Generated by Django 5.1.6 on 2025-03-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_body_postcomments_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomments',
            old_name='post',
            new_name='blogpost_connected',
        ),
    ]
