# Generated by Django 5.1.6 on 2025-03-29 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_post_postcomments_blogpost_connected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disLikes',
            field=models.ManyToManyField(related_name='blogpost_dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
