# Generated by Django 5.1.6 on 2025-04-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
